ScreenManager:
    Screen1
    Screen2
    
<Screen1>:
    name: "Home"
    BoxLayout:
        orientation:"vertical"
        padding:20
        spacing:20
        
        Label:
            id: working
            text : "OFF"
            bold:True
            font_size: 50
            halign:"center"
            size_hint:1,0.5
            
        Button:
            text: "Click To Trade" 
            pos_hint:{"center_x": 0.5, "center_y":2}
            size_hint: .3,.1
            on_press:
                working.text= "Placing Orders ..."
            on_release:
                value= app.key[0],app.key[1], app.key[2]
                working.text = f"OFF \n Come back later" if app.key[0] !="" and app.key[1] != "" else "No API key Or API Secret"
                order.text=  f"ORDER LIST \n\n\n {app.switch(value)}" 
                
        ScrollView:
            size_hint_y: None
            height: 500
            padding: 20
            Label:
                id: order
                text : "Orders Will Appear Here"
                bold:True
                font_size: 20
                halign:"center"
                size_hint:1, 0.3
          
        GridLayout:
            rows:1
            columns:2
            spacing:3
            size_hint:1,0.1
            
            Button:
                text: "Home"
                size_hint:0.1,0.1
                on_release:
                    app.root.current = "Home"
                
            Button:
                text: "Settings"
                size_hint:0.1,0.1
                on_release:
                    app.root.current = "settings"
            
      
<Screen2>:
    name: "settings"
    BoxLayout:
        orientation:"vertical"
        padding: 20
        spacing:20
        
        Label:
            text : "Settings".upper()
            halign:"center"
            bold :True
            font_size:35
            size_hint:1,.3
            
        Label:
            id: text1
            text:"API Key: "
            halign:"center"
            size_hint:1,.1
            
        TextInput:
            id: key
            hint_text: "API Key"
            size_hint:1,.1
            
        Label:
            id : text2
            text:"API Secret: "
            halign:"center"
            size_hint:1,.1
            
        TextInput:
            id: secret
            hint_text: "API Secret"
            size_hint: 1,.1
            
        Label:
            text:"Account Type"
            halign:"center"
            size_hint:1,.1
            
        GridLayout:
            rows:3
            columns:2
            size_hint:1,0.2
            
            Label:
                text:"Live"
                halign:"center"
                size_hint:1,.1
                
            Label:
                text:"Demo"
                halign:"center"
                size_hint:1,.1
        
            CheckBox:
                group:"account"
                on_active:
                    app.key[2] = ""
                    
            CheckBox:
                group:"account"
                on_active:
                    app.key[2] = "True"
        
            Button:
                text:"Save"
                size_hint:2,.5
                on_press: 
                    app.key[0] = key.text
                    app.key[1] = secret.text
                    text1.text = f"API Key: {key.text[0:3]}***************{key.text[-3:]}" 
                    text2.text = f"API Secret: {secret.text[0:3]}*************** {secret.text[-3:]}"
                    key.text = ""
                    secret.text = ""
                    
            Button:
                text:"Clear"
                size_hint:2,.5
                on_press: 
                    text1.text = "API Key: " 
                    text2.text = "API Secret: " 
                    app.key[0] = ""
                    app.key[1] = ""
                    
        GridLayout:
            rows:1
            spacing:3
            columns:2
            size_hint:1,0.1
            
            Button:
                text: "Home"
                size_hint:0.1,0.1
                on_release:
                    app.root.current = "Home"
                
            Button:
                text: "Settings"
                size_hint:0.1,0.1
                on_release:
                    app.root.current = "settings"
    